### ISSUE TITLE
"Invalid albedo value" error when no albedo values were provided

### ISSUE THREAD

**Issue by williamhobbs** [NREL/SAM#1081]
### Describe the bug

My weather file does not include an albedo column, but when I run a detailed PV simulation leaving the default "use albedo from weather file if available" option checked, I get an error.

### To Reproduce

1. Create a new detailed PV model (no financial), 
2. select my weather file that does not contain albedo values (it does happen to be a custom 1min interval weather file, see screenshot below), 
3. hit simulate,
4. get an error that there are invalid albedo values (see screenshot below)

### Expected behavior

I expected the "use albedo from weather file if available" option to not matter if the weather file does not include an albedo column.

### Screenshots

Error:
![image](https://user-images.githubusercontent.com/45701090/175573183-a2087e54-c0ed-40ab-bdc6-3f84af59eb16.png)

Weather file:
![image](https://user-images.githubusercontent.com/45701090/175573618-f29ba031-f116-403c-9749-6203f923a187.png)

### Operating System and Version

 - OS: Windows
 - Version: SAM 2021.12.2 r2

**Comment by cpaulgilman** [comment]
This issue is being caused by invalid albedo values in the Monthly Albedo table:

![image](https://user-images.githubusercontent.com/27711933/179321639-284552f8-3cec-4e6a-a2d6-79ee90706b08.png)

A workaround to fix the problem for now is to replace the invalid values of 1 with 0.2: Type 0.2 under **Enter single value** and then click **Apply**:

![image](https://user-images.githubusercontent.com/27711933/179321717-024505dc-0691-4185-86d6-c6d2da06370a.png)
