### ISSUE TITLE
Solar water heating and "electricity to grid"

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#109]
The solar water heating module "gen" quantity is calculated using "Q_saved", which is the difference between the amount of auxiliary energy required to heat the water to the set point with and without the solar water heater.  So, if for instance it takes 1000 kWh of electricity to heat the mains water to the set temperature with no solar water heating, and 400 kWh of electricity to heat the water delivered from the solar water heating system to the set temperature, than there are 600 kWh of electricity saved.  If the electric load in any hour is lower than the amount of energy saved, the model will interpret this as an opportunity to export system power to the grid, but that's clearly not what's happening.  I think perhaps we could revisit what the actual "gen" quantity coming out of the solar water heater is and whether it makes sense.

**Comment by nickdiorio** [comment]
@cpaulgilman , @n8blair , in looking at this, I think I see two options:

1. Instead of outputting `Q_saved`, output `Q_delivered`, which is the actual energy generation produced by the solar water heating system.  In this case, the full electric load, including the auxiliary heating, should go into the `Electric load` page.

2. Leave it as `Q_saved` coming out, but then the electric load should remove any auxiliary heating, as it's already accounted for.

As it is, it's admittedly confusing, and perhaps incorrect depending on what electric load is being input.

We should also probably think about whether we need to indicate a thermal to electric conversion efficiency.

**Comment by nickdiorio** [comment]
I pushed a570016c in NREL/SSC to restrict `Q_saved <= Q_load`, which should address this issue.  This assumes that the user has sufficiently defined the electric load to include all electricity required to heat the water defined by the draw.
