### ISSUE TITLE
Cambium data are in real dollars

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1098]
I was having a difficult time getting a profitable merchant plant stand alone battery to be profitable, even with a large capacity payment. I went looking at the Cambium documentation, and found that the dollar year in the data is constant:

![image](https://user-images.githubusercontent.com/5530592/180264562-3614046d-e0c3-4b84-ac48-db906b31fb6a.png)

(from https://www.nrel.gov/docs/fy22osti/81611.pdf)

Add a widget to the Cambium API download that allows users to specify inflation numbers for out-years.

**Comment by cpaulgilman** [comment]
@brtietz To be consistent with PPA price inputs for the single owner model, we could add an escalation rate input to the Cambium download form.

People have expressed interest in making Cambium price data available for the PPA financial models, so would be good to implement this an a way that would not complicate that.

Note that this is not an issue for the Merchant Plant energy and ancillary service market revenue streams because those price inputs are arrays over the lifetime. Cambium data downloads are for one year, so need to be escalated for the out years.

**Comment by brtietz** [comment]
> Cambium data downloads are for one year, so need to be escalated for the out years.

Yes. I was also thinking of the "multiple years" download feature for this case.

**Comment by cpaulgilman** [comment]
Note @mjprilliman implementation of PPI data from [Bureau of Labor Statistics](https://www.bls.gov/pPI/) for geothermal model

**Comment by cpaulgilman** [comment]
Fixed with #1365
