### ISSUE TITLE
Biopower models don't run correctly in release branch

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#111]
In the release branch of SAM and SSC the Biopower models produce NaN's for the annual energy and other metrics.

![image](https://user-images.githubusercontent.com/5658281/47167002-b5c2e980-d2ba-11e8-94d7-af14e8fc8d71.png)

We could consider whether or not the biopower module is being used enough to justify updating.  Anyone using this functionality?

**Comment by janinefreeman** [comment]
Probably not very many, but I believe @cpaulgilman gets questions about the model every now and then. I think we need to at least make the default case run... surprising that the annual energy calculation doesn't even work.

**Comment by cpaulgilman** [comment]
This fix, 94f77ee6f0cd139279afc1cbd4dda7581a516ca0 solves the problem for the default biopower case, but not for users expecting the model to work when they download a weather file from the Location and Ambient Conditions input page. A better fix is for the UI call back to check for biopower model and display a message or limit downloads to MTS1 files if a file is available for the requested location.

**Comment by cpaulgilman** [comment]
We are getting user support questions about this issue. There are a couple of things going on:

* By default, NSRDB files returned by the NSRDB API only include DNI and DHI data, but as of SAM 2018.11.11 SAM uses custom attributes for the API call that include GHI, so that issue has been resolved.

* The biomass combustion model requires relative humidity data, which is not available in the NSRDB TMY files, but is available in the single year files. Using a single-year file solves the problem of no results for biopower. 

Note that CSP and geothermal models also require relative humidity data but generate results with no error messages with NSRDB TMY files, so need to investigate further.

I've implemented some checks in the Solar Resource UI callback to provide user feedback for the biomass model for SAM 2011.11.11 r3.

**Comment by cpaulgilman** [comment]
Should change default weather file for biomass to a single-year file.

**Comment by cpaulgilman** [comment]
Biopower modules now throws a simulation error when relative humidity is not in weather file: bd2cbc310fcae8350439789a63dc436f98e6e1d5

That avoids the NaN results shown in the original description above.

Between that,  UI messages warning user when weather file does not contain humidity data, and instructions in the Help topic for the Location and Conditions input page to download single-year data from weather file, this should provide sufficient feedback to user to solve the problem.
