### ISSUE TITLE
Documentation typo in PVWatts v5 versus v7 description

### ISSUE THREAD

**Issue by kanderso-nrel** [NREL/SAM#1159]
Hardly a "bug", but the "PVWatts" page in the Help docs has a section entitled "Differences between PVWatts Version 5 and Version 7" with this sentence:

> Account for incident angle reflection losses in the module cover using the <a href="https://pvpmc.sandia.gov/modeling-steps/1-weather-design-inputs/shading-soiling-and-reflection-losses/incident-angle-reflection-losses/physical-model-of-iam/" target="_blank" class="weblink" title="https://pvpmc.sandia.gov/modeling-steps/1-weather-design-inputs/shading-soiling-and-reflection-losses/incident-angle-reflection-losses/physical-model-of-iam/">physical model</a> for incident angle modifier to account for reflection losses of both direct and beam irradiance.`

"both direct and beam irradiance" is of course redundant; I assume this should say "both direct and diffuse irradiance" or similar. 

Here is the relevant area of  the rendered HTML:

https://github.com/NREL/SAM/blob/702754d8f837fcaf7dd6a50155a5c1a013a87be2/deploy/runtime/help/html/pvwatts.htm#L90-L92

**Comment by cpaulgilman** [comment]
Yes, that should say "both direct and diffuse" I will fix this in the SAM Help source text and SAM release notes at https://github.com/NREL/SAM/blob/gh-pages/doc/releasenotes.html. The change between PVWatts V5 and V7 is that we switched to the DeSoto model (also described in Duffie and Beckman) so that the Detailed PV model and PVWatts use the same module cover model.

Note that SAM's Help system is written in Help & Manual: We generate the HTML files from that application's source files, so please continue to let us know about issues with Help rather than editing the HTML directly. (We hope to migrate to an open source platform for generating Help files at some point.)

A bigger problem with this description in Help is that SAM 2021.12.02 uses pvwattsv8 rather than pvwattsv7, so we'll need to revise that section accordingly.

For reference, the module cover model code PVWatts v5, v7, and v8 is here:

V5: https://github.com/NREL/ssc/blob/ecd6450af441ed9939198711ceab7a2bb7650ebc/ssc/cmod_pvwattsv5.cpp#L294

V7: https://github.com/NREL/ssc/blob/ecd6450af441ed9939198711ceab7a2bb7650ebc/ssc/cmod_pvwattsv7.cpp#L1091

V8: https://github.com/NREL/ssc/blob/ecd6450af441ed9939198711ceab7a2bb7650ebc/ssc/cmod_pvwattsv8.cpp#L1186
