### ISSUE TITLE
Single owner with electricity rate send to Excel with Equations 

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#123]
![image](https://user-images.githubusercontent.com/6498311/48298127-f4406400-e474-11e8-9f2f-80cec7d2aa95.png)

**Comment by sjanzou** [comment]
Fixed with commit 0513dcaf939a79263211b3c2029610013d116d7e

**Comment by cpaulgilman** [comment]
Need to revisit this for generic system / single owner with battery and electricity rate. Also need to more fully test send to excel with equations for all battery scenarios.

**Comment by cpaulgilman** [comment]
> I noted right now that the financial metrics in SAM seem to be a bit strange so I exported the cash flow in excel and I discovered that there remarkable differences, the most important seems to concern the NPV.

[GenericBattery_Standalone_2020.zip](https://github.com/NREL/SAM/files/4541023/GenericBattery_Standalone_2020.zip)

> This is what SAM returns:

![image](https://user-images.githubusercontent.com/27711933/80399291-d257be80-886d-11ea-8307-28f0ae938d44.png)

> This is what excel returns for the same case:

![image](https://user-images.githubusercontent.com/27711933/80399314-db489000-886d-11ea-96bb-c907756f2cf7.png)

> I think that excel is providing correct values, right?

**Comment by sjanzou** [comment]
The issue was with cashflow.lk missing sending electricity purchase as o and m. Fixed and merged into patch and develop branches from SAM_123 branch.

![image](https://user-images.githubusercontent.com/6498311/80478274-8a3aa980-890a-11ea-87ab-977b75297d4f.png)
![image](https://user-images.githubusercontent.com/6498311/80478296-91fa4e00-890a-11ea-8bb3-88a31c9ce57c.png)

**Comment by cpaulgilman** [comment]
For default Generic Battery / Single Owner in both SAM 2020.2.29 r1 and build from Patch branch:

![image](https://user-images.githubusercontent.com/27711933/80839075-592ed300-8baf-11ea-8ef4-51cdfe96e9f6.png)

**Comment by cpaulgilman** [comment]
Working on this. There are a few issues:

* Battery replacement cost input is on O and M Costs UI form, and is `om_replacement_cost1` and `om_replacement_cost_escal`, not `battery_replacement_cost`. This needs to be fixed in cashflow.lk and in all of the workbooks in the `spreadsheets` folder except PV_for_India.xlsx, 

* Also need to fix fuel cell operating costs. Those are defined on a separate Fuel Cell O and M Costs and include fuel-cell specific variables like `fc_fuel_cost`, `om_capacity1`, `om_capacity2`, `om_fixed1`, etc. that need to be added to cashflow.lk and to the workbooks in the `spreadsheets` folder for Commercial and Single Owner (fuel cell is only available with those financial models).
