### ISSUE TITLE
Upgrade Latin Hypercube Sampling library

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1236]
We're due to upgrade the LHS library from Dakota, as that pairs well with the new uncertanty features in this release: https://dakota.sandia.gov/download.html

Additionally, best practice would be to link directly to the libraries via CMake, rather than running them as an external executable. The LGPL licensing means we need to work from the latest binaries, rather than compiling from source.

**Comment by sjanzou** [comment]
@brtietz , since the Dakota binaries are provided as x86_64 only, using the binaries breaks our Apple Silicon universal binary and will require users install Rosetta to run SAM. I can test the binary for CentOS as mentioned on the link but may have issues as well. Also, stepwise.cpp and stochastic.cpp and pvuncertainty.cpp will need to be rewritten for the updated Dakota calls instead of using files that were used with the executables.

**Comment by sjanzou** [comment]
@brtietz , what is the final verdict on this after meeting with legal? Are we building for Apple Silicon without modification?

**Comment by brtietz** [comment]
Yes, that was the verdict.
