### ISSUE TITLE
Stagger multiple site production start dates over different months and years

### ISSUE THREAD

**Issue by ErieRenaissance** [NREL/SAM#1294]
It would be great if there was an option to indicate the month & year each site system comes online when using a generic model for multiple sites. So that the financial model would show partial production periods and stagger when each site begins production. For example, if system A comes online in June Y1, the financial reporting would only show values for months 6-12.

If project has 2 sites and system B comes online in May of Y2, the report would show values for Site A for months 6-12 in Y1 & months 1-4 in Y2, but Sites A & B for months 5-12. And so on

**Comment by cpaulgilman** [comment]
@ErieRenaissance SAM is designed to model a single project at a given site, so this may be a bit beyond the scope of what SAM can do.

The cash flow models are based on annual cash flows, so there is not a way to show changes to the cash flow on a monthly basis.

For the Generic System model, you could import a time series generation profile that represents different systems coming on line as the year progresses, but because the generation profile input is over a single year, this would model the same system(s) coming on line every year over the analysis period. It is not possible to use that approach to represent different systems coming online in different years over the analysis period.
