### ISSUE TITLE
Grid outage causes simulation to hang at around 30%

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1324]
### Describe the bug

See https://sam.nrel.gov/forum/forum-general/4119 for a description and sample file.

Link to sample file: https://sam.nrel.gov/forum/attachment/1421

From @brtietz:

> ...the grid outage code should always finish. If the system is too small, the extra load should be recorded as unmet critical load. There are some while loops in there that should converge, but it looks [this is] a case where they don’t.

### To Reproduce

1. Open file attached to forum topic above.
2. Go to the 30 kW case.
3. Click **Simulate**.

Simulation starts but then progress bar stops at around 30%.

### Expected behavior

Simulation should finish and results should show unmet critical load.

### Operating System and Version

 - Tested on Mac and Windows
 - SAM 2022.11.21

**Comment by brtietz** [comment]
The issue was a specific combination of PV generation and critical load where the powerflow code would swap from not dispatching the battery to charging the battery, while the battery was at 100% already. I've cleaned up the powerflow code so key variables now can't go negative, and this solves the problem. Pull request coming soon.
