### ISSUE TITLE
Diurnal Period widget with more than 12 periods

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#1354]
### Describe the bug

SAM crashes when the Diurnal Period widget attempts to load a schedule with more than 12 periods, such as in the attached tou-24-periods.csv. Importing the data into SAM 2022.11.21 causes it to crash, but it works fine in SAM 2021.12.02 r2.

[tou-24-periods.zip](https://github.com/NREL/SAM/files/10769070/tou-24-periods.zip)

### To Reproduce

1. Create a PVWatts / Commercial case.
2. On the Electricity Rates page, click Load rate from file (button toward top of page) and open attached tou-24-periods.csv file.
3. SAM 2022.11.21 briefly displays an error message (msgbox from a UI callback) and then crashes.

### Expected behavior

Should behave like SAM 2021.12.02 r2, which opens the rate with a TOU schedule like this (no color for those numbers greater than 12 is fine for now):

![tou-24-periods](https://user-images.githubusercontent.com/27711933/219717837-bcf0c098-6a7b-421c-9c54-16a3fb4f4b5f.png)

### Operating System and Version

 - Tested in SAM 2022.11.21 for Windows

### Additional context

This is likely related to changes made to the widget to adapt it to represent ground albedo [here](https://github.com/NREL/wex/blob/7476aac30af3b9934679d67309fc56b8acef270d/src/diurnal.cpp#L231), introduced by changes to support using the widget to represent ground albedo in https://github.com/NREL/wex/pull/145.

Fixing this problem is required to address https://github.com/NREL/SAM/issues/28.

**Comment by sjanzou** [comment]
@cpaulgilman , @brtietz 
Addressed in SAM_1354 branches of wex and SAM
wex pull request https://github.com/NREL/wex/pull/157
SAM pull request https://github.com/NREL/SAM/pull/1356

Warning message appears due to two variables in the tou-24-periods.csv rate file that are no longer used:
![image](https://user-images.githubusercontent.com/6498311/219863930-845b5e3a-0722-45e2-a11d-f815d4f84f4f.png)

Please use the following rate file to test:
[tou-24-periods_update_billing_demand.zip](https://github.com/NREL/SAM/files/10774041/tou-24-periods_update_billing_demand.zip)

**Comment by Matthew-Boyd** [comment]
Thanks @sjanzou !
