### ISSUE TITLE
PV capital cost curves only update on load

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#1383]
### Describe the bug

The page only updates the cost if you look at the page. We'd expect it to change on relevant variables like DC or AC system size

### To Reproduce

1. Set up a case in SAM using the PV cost curve
2. Duplicate the case
3. Change the system size in the 2nd case
4. The systems have the same total installed cost

### Expected behavior

The PV cost curves page should update the system costs any time the typical system costs page would. This likely requires additional on_change functions.

**Comment by mjprilliman** [comment]
@cpaulgilman I think when I originally implemented this my understanding of the variable flow wasn't as strong. The on-the-fly updates for these cost tables with the system capacities makes me think this should be shifted to a MIMO (or ssc_eqn) with the warning label updates remaining in callbacks. Thoughts?

**Comment by cpaulgilman** [comment]
> @cpaulgilman I think when I originally implemented this my understanding of the variable flow wasn't as strong. The on-the-fly updates for these cost tables with the system capacities makes me think this should be shifted to a MIMO (or ssc_eqn) with the warning label updates remaining in callbacks. Thoughts?

I think it makes sense to move the cost calculations to MIMO equation functions on the Capex Table xxx UI forms so that the total installed cost is recalculated when the capacity changes on the System Design page. Unless we want to make the capex tables inputs to SSC compute modules, I think these can stay in the UI rather than be moved to ssc_eqn. These are purely UI calculations and don't involve running an SSC module.
