### ISSUE TITLE
simulate() function of lk script not working

### ISSUE THREAD

**Issue by nickdiorio** [NREL/SAM#148]
In the attached SAM file and script, the `simulate()` function of an LK script is not behaving as expected.  No errors are reported, but the case does not simulate.

[make_plots.zip](https://github.com/NREL/SAM/files/2741567/make_plots.zip)
[Analysis-singleowner-1min.zip](https://github.com/NREL/SAM/files/2741568/Analysis-singleowner-1min.zip)

To reproduce:
1. Unzip the files 
2. Open the SAM file in the `fuel_cell` branch for SAM and SSC
3. Point to the attached weather file in the SAM case
4. Open the `make_plots.lk` script within SAM.
5. Run the script.

**Comment by cpaulgilman** [comment]
Tested in SAM 2020.2.29 Patch 1 (prerelease version) and could not replicate. Simulations take a long time because of the one-minute time step, and "pvwattsv7 failed to process irradiance on surface" error for one time step triggers simulation fail message, but simulations do finish and plot functions work.

![image](https://user-images.githubusercontent.com/27711933/77780747-b4e6c900-7011-11ea-989c-4bdb55128f77.png)
