### ISSUE TITLE
Results button resetting when linked hybrid variables are reloaded

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#1485]
### Describe the bug

-After clicking Simulate, if an input page with a dependent input variable (system_capacity, total_installed_cost, etc.) is loaded, the Results button to view previously simulated results is deactivated and cannot be clicked. This is fine functionally but is not immediately clear to the user when it happens. 
### To Reproduce

1. Go to Hybrid case
2. Hit Simulate
3. Click on PV System Design
4. Try to Click Results button next to Simulate

### Expected behavior

-Not clear what the expected behavior should be. Perhaps a Tooltip or a change in color for the button when it is not active.

**Comment by cpaulgilman** [comment]
A possible solution would be to clear results instead of disabling the Results button so that users get some feedback from the message in the Metrics table when they click the Results button:

![image](https://github.com/NREL/SAM/assets/27711933/aa64514a-5927-4e21-ba21-50e5e60ceb52)

This is still a bit confusing, because it isn't clear why the results are cleared, but is better than no feedback.
