### ISSUE TITLE
wxWidgets 3.2.3

### ISSUE THREAD

**Issue by sjanzou** [NREL/SAM#1538]
Update to latest stable wxWidgets version 3.2.3 released 10/10/2023 for all platforms

https://wxwidgets.org/downloads/

**Comment by brtietz** [comment]
Upgrade worked for me with no code changes.

Streamlined steps for other Windows users:
1. Download from Steve's link above, otherwise follow instructions under step 2 with 3.2.3 as the version number instead of 3.2.0: https://github.com/NREL/SAM/wiki/Windows-Build-Instructions
2. After a successful build, skip to step 6 and update the env path
3. Re-run CMake
4. Rebuild SAM as normal (will take about as long as a full build)

PR https://github.com/NREL/SAM/pull/1540 updates GitHub Actions and should be pretty informative about the magnitude of change required for the Mac and Linux builds.

Close this issue after all developers have upgraded and the build instructions are up to date.

**Comment by dguittet** [comment]
Upgrade worked for me on Mac Apple Silicon

**Comment by sjanzou** [comment]
wxWidgets 3.2.3 updated and working on Windows 11, REHEL 8.6, and macOS 14 and fixed issue #1482

**Comment by cpaulgilman** [comment]
Build instructions for Windows, Mac, and Linux updated to describe wxWidgets 3.2.3, Linux instructions replace CentOS 7 with RHEL 8.

I built and ran open source versions of SAM with wxWidgets 3.2.3 on Windows 10 and Linux Mint 21.1.

**Comment by tyneises** [comment]
Works for me

**Comment by qualand** [comment]
Works for me
