### ISSUE TITLE
 Fronius Symo Advanced 17.5-3-M missing

### ISSUE THREAD

**Issue by andreas-bulling** [NREL/SAM#1822]
The above inverter is missing in the database - it's the last one missing from Fronius' latest "Advanced" series.

https://www.fronius.com/de/solarenergie/installateure-partner/technische-daten/alle-produkte/wechselrichter/fronius-symo-advanced/symo-advanced-17-5-3-m

**Comment by cpaulgilman** [comment]
@andreas-bulling We build SAM's inverter library from the data in the "Grid Support Solar/Battery Inverters" list from the California Energy Commission. You can see the inverter list and download the Excel file we use to build the library here:

https://solarequipment.energy.ca.gov/Home/InvertersList

This list includes and inverter listed as "Fronius Symo 17.5-3 480 [480V]" but does not have a 17.5 model listed as "Fronius Symo Advanced," which is why the SAM inverter library does not have an inverter named "Symo Advanced 17.5-3".

We build SAM's module and inverter libraries once a year with the release of each new version of the software. You can find the CEC Excel workbook and other files we use to build the libraries on GitHub. For example, the files used to build the inverter library for SAM 2023.12.17 are here:

https://github.com/NREL/SAM/tree/patch/samples/CEC%20Module%20and%20Inverter%20Libraries/CEC%20Inverters/CEC%20Inverters%202023-11-17

You can find contact information for the CEC solar equipment lists on their website:

https://www.energy.ca.gov/programs-and-topics/programs/solar-equipment-lists

**Comment by andreas-bulling** [comment]
Thanks a lot. I contacted them and requested to have this inverter added to their database. So hopefully it will eventually also end up in SAM
