### ISSUE TITLE
x Axis scale not correct on 2020.1.17 beta for hourly graphs

### ISSUE THREAD

**Issue by frohro** [NREL/SAM#247]
Hi,
I'll enclose some screen shots.  One will be okay, and will come from the 2018.11.11 version and the other will be from the 2020.1.17 beta.  The x-axis is all messed up.
Thanks,
Rob
![image](https://user-images.githubusercontent.com/994565/74420554-5cab9b80-4e97-11ea-8427-f49644b4b442.png)
![image](https://user-images.githubusercontent.com/994565/74420606-72b95c00-4e97-11ea-9997-fdff96b513c9.png)

**Comment by sjanzou** [comment]
The issue was that the minimum x value was not initialized properly and has been updated and fixed with commit 2215ed4d0559df1cda703bfd72831824f18f1146. Also, adding multiple bar plots to the same graph was timing out in 2018.11.11 and has been fixed in this commit, too.
![image](https://user-images.githubusercontent.com/6498311/74833208-3e4e0180-52d6-11ea-88f4-446bf3ff258c.png)

**Comment by frohro** [comment]
Thanks for your quick fixes!
Rob
