### ISSUE TITLE
Not all changes in files opened in 2020.2.29 from previous versions get flagged....

### ISSUE THREAD

**Issue by frohro** [NREL/SAM#255]
Sorry I don't have the time right now to properly submit this bug report with simplified examples, but I thought it worth at least giving you a "Heads up!" with the time I have.

I opened a file from 2020.1.17 using 2020.2.29 and found most of the battery settings were changed, though only one was called out in the nice list of possible issues when you open a file from an older version.  I'll enclose the 2020.1.17 file here.[Report_Simulations.zip](https://github.com/NREL/SAM/files/4315463/Report_Simulations.zip)
 
I like the idea that you have a flagging system for what changed, but if it doesn't flag everything it can be very misleading.

**Comment by cpaulgilman** [comment]
Thanks. I started a list of battery inputs that need to be properly handled in the upgrade.lk script and will do further testing to catch others. Please add to this list if you notice other items:

* Front-of-meter electricity rates: If enabled in 2018.11.11 should import as enabled in 2020.2.29.

* Set dispatch model.

Thanks,
Paul.

**Comment by cpaulgilman** [comment]
This has been fixed in https://github.com/NREL/SAM/commit/582535335ae6571489a044f1f7b0de640cc2a9f6

### For the record: 

The solution was to create a new config_update_with_old_variables() for the internal versions.lk script that we use to update variables as necessary between versions. For example, using SAM 2020.2.29 to open a Detailed PV / Single Owner with battery enabled case created in SAM 2018.11.11 r4:

1.  "Flat Plate PV /Single Owner" configuration from 2018.11.11.r4

2. Upgrades to a valid configuration "Flat Plat PV/Single Owner" in 2020.2.29 with none of the battery variables since those are now in the PV Battery technology. So, all of the variables from the 2018.11.11.r4 "Flat Plat PV/Single Owner" that are not in the 2020.2.29 "Flat Plat PV/Single Owner" configuration are moved to the `OldValues` VarTable for that case.
 
3. The version upgrade script then changes the configuration to "PV Battery / Single Owner". So, the variables that are in the "PV Battery/Single Owner" configuration that are not in the "Flat Plate PV / Single Owner" configuration in 2020.2.29 are overwritten with the default values. 

So, to update the changed configuration with the `OldValues` varTable case you would need to go through all of those values and map to the new configuration. With the new `config_update_with_old_variables()` (`config()` is still available to change configuration without updating variables), to perform an upgrade from an old project file with the  "Flat Plat PV / Single Owner" with battery storage enabled:

1. Use `config()` to change configuration.

2. Use `config_update_with_old_variables()` to update any variables in new configuration that are no longer in original configurations that was updated.
