### ISSUE TITLE
Grid limits do not apply to empirical trough outputs

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#257]
https://sam.nrel.gov/forum/forum-general/2946-grid-limits-for-csp-empirical-trough-model

[grid_limit_empirical_trough.zip](https://github.com/NREL/SAM/files/4340739/grid_limit_empirical_trough.zip)

**Comment by janinefreeman** [comment]
Adding context from an older email discussion so it's attached to this issue:
•	The grid compute module appears not to be hooked up correctly for some CSP models. 
•	We can’t just remove the grid compute module, because outputs from it (curtailed energy) are required for the financial models.
•	The most correct solution would be to make curtailed energy etc. optional in the financial models, and then have them conditionally appear in cashflows. However, that may be pretty difficult.
•	Therefore, the next best proposed solution:
o	Make the grid cmod a pass-through if the variables aren’t assigned
o	Remove the grid page and the curtailment value page from the UI for the CSP models that aren’t working
