### ISSUE TITLE
Battery bank sizing - Specify cells

### ISSUE THREAD

**Issue by andremosfet** [NREL/SAM#267]
"Specify cells" section doesn't work  in SAM 2020.2.29 version for Windows 7.
Nominal battery capacity dosen't change modifying number of cells in series/parallel.

**Comment by cpaulgilman** [comment]
Please let us know if you see the same behavior in SAM 2020.2.29 r1, and if you do, please attach a .sam or post screenshots that illustrate this issue. I was not able to replicate it in either SAM 2020.2.29 or SAM 2020.2.29 r1. We did fix some problems with the UI form for the Battery Storage page in Revision 1.

**Comment by andremosfet** [comment]
I installed SAM 2020.2.29 r1 and I experiencing the same issue.
It seems that "cell in series" value is not updated accordingly to the UI input (Number of cell in series). No problem with the Parallel values. See attached screenshot.
![CellsinSeries](https://user-images.githubusercontent.com/19230102/78247991-1d3f1a00-74ec-11ea-907c-83a2fbed5636.jpg)

**Comment by andremosfet** [comment]
I installed SAM 2020.2.29 r1 and I experiencing the same issue.
It seems that "cell in series" value is not updated accordingly to the UI input (Number of cell in series). No problem with the Parallel values. See attached screenshot.

![CellsinSeries](https://user-images.githubusercontent.com/19230102/78247991-1d3f1a00-74ec-11ea-907c-83a2fbed5636.jpg)

**Comment by cpaulgilman** [comment]
This is an issue for behind-the-meter (BTM) but seems to be working for front-of-meter (FTM) configurations. Need to be sure to test fully for BTM, FOM, PV-battery, and Generic-battery configurations.

**Comment by cpaulgilman** [comment]
The issue is that there is a typo in the "Number of cells in series" variable name `batt_bank_ncells_serial` on the Battery Bank Sizing with REopt UI form that is used for BTM configurations. For Patch 2 we should fix the typo and put the REopt input and text on its own form so we can use one battery sizing form for both BTM and FOM.

Here is a workaround for SAM 2020.2.29 r1:

1. If SAM is running close it.

2. In the [SAM installation folder](https://sam.nrel.gov/forum/forum-general/2776-sam-installation-folder.html), replace `Battery Bank Sizing with REopt.txt` with [Battery Bank Sizing with REopt.txt](https://github.com/NREL/SAM/files/4424067/Battery.Bank.Sizing.with.REopt.txt).

3. Start SAM and create or open a Detailed PV-Battery case with Residential, Commercial, or Third Party - Host Developer financial model. 

4. Go to the Battery Storage page, and verify that **Cells in series** and other calculated values under "Computed Properties" change when you choose **Specify cells** and type different values for **Number of cells in series**.

**Comment by andremosfet** [comment]
It's working really good now.

Thanks

**Comment by cpaulgilman** [comment]
Some other battery user interface things to fix or improve:

* Variables that are choices (radio buttons, list boxes, etc.) need Index Labels variable property to match List widget property to display properly in inputs browser, parametric inputs selection window, etc. For example battery cycle cost choice for FOM dispatch.

* Several variables or options have confusing labels like "Automated dispatch: Input forecast," which would be clearer as "Automated dispatch: Custom weather file."

* Fix alignment of user interface elements and reorganize some groups of variables to clarify relationships.
