### ISSUE TITLE
LK contour() function causes SAM to crash

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#306]
The following test script runs in SAM 2018.11.11 r4 but not in SAM 2020.2.29:

[contour_test.zip](https://github.com/NREL/SAM/files/4624810/contour_test.zip)

**Comment by sjanzou** [comment]
Trace to setting axis reversed in contour plot before axes were created from lkscript call. Fixed in lkscript.cpp in SAM_306 branch of wex and merged into develop and patch branches of wex.
![image](https://user-images.githubusercontent.com/6498311/82038809-54632800-9661-11ea-8228-fea412e51021.png)

verify reversed y axis in marine energy wave results
![image](https://user-images.githubusercontent.com/6498311/82038888-693fbb80-9661-11ea-99b7-99222dc10d9e.png)

**Comment by cpaulgilman** [comment]
Tested SAM 2020.2.29 r2rc on Ubuntu 18.04.3 LTS
