### ISSUE TITLE
Code generator fails with "input ordering failed" message.

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#307]
To replicate:

1. Create a PVWatts / Residential or a PVWatts / Third Party Host case.

2. Click **Generate code** and choose any language. 

The error seems to only be generated for Residential or Third Party Host with PVWatts. It works fine with Detailed PV and Wind, for example. PVWatts with other financial models work. 

This is not an issue in SAM 2018.11.11 r4

**Comment by sjanzou** [comment]
Trace issue through to input variables and number of compute modules called.
![image](https://user-images.githubusercontent.com/6498311/82046300-de18f280-966d-11ea-87ae-c513b07cf665.png)

Issue was in startup.lk that PVWatts configurations without batteries was still calling 'battwatts' and some configurations had battwatts inputs and some did not.

Solution was to remove all 'battwatts' from setmodules in startup.lk for all PVWatts configurations without batteries.
![image](https://user-images.githubusercontent.com/6498311/82046473-3223d700-966e-11ea-8825-f6a031accc07.png)

fixed in patch and manually into develop

**Comment by cpaulgilman** [comment]
Tested release candidate in Windows 10.
