### ISSUE TITLE
SAM 2020 CRASHING after selecting PV detailed project mode 

### ISSUE THREAD

**Issue by pmthorat1594** [NREL/SAM#314]
Hello, 

I am trying to use SAM 2020 to generate sub hourly output. I selected the weather file from solar anyhwere to be imported into SAM and It has been crashing ever since then after I launch the PV detailed project mode. 

Kindly help me resolve this issue. 

Thank you

**Comment by cpaulgilman** [comment]
Hello,

Are you using the Solar Resource File Converter macro to convert the SolarAnywhere file to SAM CSV before running a simulation?

If you are reporting a bug, please provide sample files and steps to replicate the issue. You can put .sam and .csv files in a zip archive to attach to your post.

If you need help getting your SolarAnywhere file to work with SAM, please use the SAM Forum to post your question or comment: https://sam.nrel.gov/forum.

Thanks,
Paul.

**Comment by pmthorat1594** [comment]
Hello Paul,

Thank you for responding to my query. After the initial issue with the weather file, now SAM has been crashing as soon as I open the PV detailed mode. I cannot do anything further apart from just starting SAM. I have tried uninstalling and reinstalling the software. That didn’t work.

Kindly request you to help me resolve this issue.

Thank you,

Sincerely,

Prathamesh Thorat | Performance Specialist | +1 949 398 3915 | prathamesh.thorat@baywa-re.com<mailto:prathamesh.thorat@baywa-re.com>

**Comment by cpaulgilman** [comment]
Could you provide a copy of the weather file?

SAM may be crashing if there is a problem with the weather file and it is in one of the folders that it uses to build the Solar Resource library file.

Please try the following:

If you used the **Add/remove weather file folders** button on the Location and Resource page to add the file that contains the weather file, please move the file to a different folder. Otherwise, if the file is in _<user>/SAM Downloaded Weather Files_ folder, please remove it from there.

Best regards,
Paul.
