### ISSUE TITLE
"DC Adjust" losses being applied even if "enable" checkbox is not checked

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#335]
To replicate:
1. Create a detailed PV/no financials case
2. Go to the losses page
3. Click "Edit losses" for the DC Losses at the bottom of the page
4. Enable hourly losses with custom periods and enter a non-zero loss (change the period also to make it obvious)
5. Run the simulation and note the annual energy
6. Go back to the losses page and uncheck "enable hourly losses with custom periods" without zeroing out the inputs
7. Run the simulation and note the annual energy is the same as if the loss was enabled
8. Go back to the losses page, enable the custom periods, change the loss to zero, and disable the custom period again
9. Run the simulation and note that the annual energy goes back up to its original value

The same bug does not appear to apply to the "AC Losses" input on the same page.

**Comment by cpaulgilman** [comment]
Fixed in https://github.com/NREL/ssc/commit/55b99b4a7a85de2bffdc4e632f253746f4c00044

The loss adjustment table require field must be set for the values from the widget to be set correctly.

**Comment by cpaulgilman** [comment]
@dguittet  and @sjanzou: This fix broke the generic system model because dc_adjust is an input to cmod_generic_system, but the SAM UI does not assign a value to dc_adjust, so the missing required input dc_adjust:constant causes the simulation to fail.

I'm investigating, but think the solution is to remove the dc_adjust input because generic_system assumes an AC generation profile, and generic_system with battery assumes an AC-connected battery, so a DC loss should never be applicable.
