### ISSUE TITLE
Merchant plant does not generate revenue

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#346]
For example, this [file created in SAM Beta 2019.12.2](https://github.com/NREL/SAM/files/4919630/Merchant.zip), SAM 2020.2.29 generates this error:

> exec fail(merchant plant): The generation is not sufficient to meet the ancillary markets requirements.  Specifically, energy market cleared capacity -0.006 is less than zerod at timestep 0
> Simulation merchantplant failed :exec fail(merchant plant): The generation is not sufficient to meet the ancillary markets requirements.  Specifically, energy market cleared capacity -0.006 is less than zerod at timestep 0

Note negative grid power at night due to inverter nighttime consumption.

**Comment by sjanzou** [comment]
Fixed with branch SAM_346 in ssc - issue with constraint checking and with defaults to match the revenue generated
![image](https://user-images.githubusercontent.com/6498311/88652809-8690fd00-d088-11ea-94b6-6a3b08898c4a.png)

with project file and workbook validation per attached zip file.
[SAM_346.zip](https://github.com/NREL/SAM/files/4987580/SAM_346.zip)

**Comment by cpaulgilman** [comment]
Thanks, Steve. Note that the original file posted in my first post above has grid curtailment 8760 array set to zeroes (on the Grid Limits page) instead of 1e38, which causes a simulation error.
