### ISSUE TITLE
Separate O&M Costs for PV + Battery Systems

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#355]
See https://sam.nrel.gov/forum/forum-general/3065 about a request for O&M costs to scale with battery size, separate from PV.

From duplicate issue #169:

> Add $/kW for battery replacements to be consistent. Currently, battery replacements are specified on a $/kWh basis, while battery costs on the System Costs page are $/kW and/or $/kWh.

**Comment by cpaulgilman** [comment]
See also https://github.com/NREL/SAM/issues/169

**Comment by brtietz** [comment]
See also https://github.com/NREL/ssc/issues/257

**Comment by brtietz** [comment]
This requires additional variables in SSC such that these O&M costs can be broken out as line items in the cash flow sheets.

**Comment by sjanzou** [comment]
@cpaulgilman have you updated the UI for this layout and, if so, on what branch? Thanks!

Latest, in develop: 
![image](https://user-images.githubusercontent.com/6498311/96080500-6f3a0280-0e74-11eb-8b22-c45f681b6aa0.png)

**Comment by cpaulgilman** [comment]
@sjanzou @brtietz Does this require adding a new SSC variable for battery replacement cost in $/kW (maybe use single escalation rate for both battery replacement costs) before I add an input to the UI?

**Comment by sjanzou** [comment]
@cpaulgilman, yes, a new variable that will be passed to ssc from the O and M UI and used to calculate another cashflow line item in all financial models that support battery configurations. So, choose the name you like - will be used for SAM, ssc, and the Excel workbooks with equations!

**Comment by cpaulgilman** [comment]
Current implementation of O&M costs is hacky (see especially fuel cell O&M costs), so we want to do a systematic refactoring of the O&M cost code before adding the new battery O&M cost as part of levelized cost of storage (LCOS) project. Notes from 10/22/2020 meeting:

* Use single $/kW value for battery O&M cost.

* Consider replacing SSC variable names like `om_capacity1` with more meaningful names like `om_capacity_battery` to make it easier for SDK users to understand variable names.

* Consolidate variable assignments into one place (common.cpp?) rather than in each financial model (singleowner.cpp, etc.) so that these variables are available to all technology and financial models as needed.

* Treat "normal" O&M costs, fuel cell O&M costs, biopower feedstock costs, and CSP fuel costs in a consistent way.

* Make sure O&M costs are shown correctly in the cash flow for all financial models, and in send-to-Excel with Equations spreadsheets.

* Update versions.lk to handle any variable name changes.
