### ISSUE TITLE
Subhourly EPW weather files generating shading error

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#365]
Several users are reporting a pvsamv1 error when using subhourly EPW weather files from:

```
exec fail(pvsamv1): Error calculating shading factor for subarray 0 at index 0
Simulation pvsamv1 failed :exec fail(pvsamv1): Error calculating shading factor for subarray 0 at index 0 
```

Workaround is to use Solar Resource File Converter macro to convert from EPW to SAM CSV format, but we should figure out what is causing this.

https://sam.nrel.gov/forum/forum-general/3102

https://sam.nrel.gov/forum/forum-general/3095

**Comment by mjprilliman** [comment]
@cpaulgilman @dguittet 

EPW files based on TMY or TMY2 data from EnergyPlus and Climate One Building have minutes = 60. This is meant to represent that the timestep describes the hour following the hour (11:00:00 - 11:59:59). But this is also meant in TMY3 epw files, where the minute is 0. So I think the minute for TMY or TMY2 epw files (always hourly) should be changed to 0. 

Work is in branch subhourly_epw_shading in ssc. 

https://discourse.radiance-online.org/t/meaning-of-epw-files-minute-field-and-why-is-it-60-in-tmy2-based-epw-and-0-in-tmy3-based-epw/1462/3

**Comment by cpaulgilman** [comment]
@mjprilliman It might be worth checking that the [weather file converter](https://github.com/NREL/ssc/blob/develop/ssc/cmod_wfcsv.cpp) is handling time steps correctly in the EPW to SAM CSV conversion process.

I also think we should try to move toward requiring SAM CSV files for SSC, especially if other formats are changing over time. Instead we could support development of tools for converting files from other formats to CSV. SSC has the wfcsvconv class, and SAM has the Solar Resource File converter macro, which uses the SSC functions to convert TMY, TMY2, and EPW, and has its own code for other formats like SolarAnywhere, and PVsyst, and others. Perhaps these could all be consolidated into a Python script or package.

**Comment by cpaulgilman** [comment]
@mjprilliman I just asked for test files here: https://sam.nrel.gov/forum/forum-general/3185.

**Comment by dguittet** [comment]
Thanks @mjprilliman for tracking down how to interpret these different timestamps.

@cpaulgilman I think the problem is that if either our weather processing changes or other weather formats are changing, we'll still have to understand how to ingest their data (e.g., interpret their time stamp meaning and how that can be aligned with SAM's). 

I think that ingestion should still live in `lib_weatherfile` where it can be used to both natively read EPW files and convert them via `weatherfile::convert_to_wfcsv`. I'm looking at that conversion code now and indeed it doesn't do any duplicate/potentially-conflicting interpretation of the input file. However it may not have been updated for sub-hourly files...

**Comment by mjprilliman** [comment]
@dguittet @cpaulgilman I'm a bit confused on the remaining action items here? The convert_to_wfcsv function does not take the minutes into account when converting to SAM csv format so I suppose in its current state it cannot be used to convert subhourly weather files? Changing the 60 minute input to 0 to better define the time stamp removes the errors from the start of the issue.
