### ISSUE TITLE
Add transient thermal model option to the UI, documentation

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#380]
Transient thermal model (Prilliman, 2020) included in the SSC, need to include option to choose it in SAM UI. Also update documentation with details of transient thermal model.

**Comment by dguittet** [comment]
@cpaulgilman documentation in SAM Help of the Transient thermal model. Should we also include option of turning on or off in UI?

User adding PV mass (not available in CEC data) could be in the future.

**Comment by cpaulgilman** [comment]
@mjprilliman One possibility would be to add the module mass as an input in the "Temperature Correction" group on the Module input page instead of having it hard-coded in the SSC code. 

* The input would have a default value of the current hard-coded value, but the user could change it if they want. 

* The input would be disabled unless the weather file time step is 20 minutes or less.

* If the time step is 20 minute or less, enable the input and display a message in the UI explaining that the transient model applies.

In the future, if module weight becomes available in the CEC database, we could read it from the module library.

**Comment by mjprilliman** [comment]
@cpaulgilman Do you think this input should be included for all of the PV Module models (CEC, 6par, SNL, SPE, sd11par)? Right now I've done work to have it included in the first 3.

**Comment by cpaulgilman** [comment]
@mjprilliman The most frequently used are cec and 6par, so the first three is fine for now. We may get feedback to add it to sd11par, which we could do later.

**Comment by mjprilliman** [comment]
@cpaulgilman Any idea on why the 6par model is not touching the transient model even when the time step says it should? This is happening in the release and in develop

**Comment by cpaulgilman** [comment]
@mjprilliman Is "6par" the 6parsolve compute module? That is the coefficient generator, not a module model that is called during the simulation.

**Comment by mjprilliman** [comment]
@cpaulgilman That is what I was calling the CEC User specified model as the variables were all labeled with 6par

**Comment by cpaulgilman** [comment]
@mjprilliman Right. The "CEC user-specified" model in the user interface isn't really a separate module model than the "CEC database" model. Both are the same model but the "user-specified" option uses coefficients from the input page (as calculated by the 6parsolve module) instead of coefficients from the CSV module library file. Sorry my original reply above was misleading.

**Comment by mjprilliman** [comment]
@cpaulgilman Thanks for the clarification. I was speaking more in the sense of the module_model value (1 for CEC Database, 2 for CEC User Specified). It seems like something is being handled differently at some point in the workflow as the CEC Database has different celltempSS and celltemp outputs regardless of NOCT or heat transfer method choice, while the CEC User specified has celltempSS = celltemp in develop and in the release version.

**Comment by mjprilliman** [comment]
@cpaulgilman @dguittet When MPPT Clipping occurs in pvsamv1, the voltage is recalculated and subsequently the temperature model is recalculated, overwriting the variable containing results of the transient thermal model. The transient model is not run again for the clipped calculation.
