### ISSUE TITLE
System Sizing Macro Fails 

### ISSUE THREAD

**Issue by brtietz** [NREL/SAM#464]
For the default singleowner case, the system sizing macro fails with the following error message:

```
Getting input parameters.
Running simulation to get operating voltages.
Setting up scenarios.
Generating design suggestions  based on 25239 modules in library.
Macro did not finish.
[592] runtime exception at line 592: access violation: expected array for indexing, but found null
```

Not sure if this is due to the default size changes, or the updated module/inverter library changes.

**Comment by mjprilliman** [comment]
I think my library updates (from today) fix the macro. I am getting this error:

![image](https://user-images.githubusercontent.com/54449384/100272602-ad691e00-2f18-11eb-8188-8ee65b54de67.png)

But that seems like a administrator issue rather than a SAM issue. 
I will check the rest of the macros and make sure the library is still doing everything its supposed to later this afternoon.

https://github.com/NREL/SAM/pull/466 for the PR
