### ISSUE TITLE
Some Windows users get a VCRuntime140_1.dll missing error when launching SAM after installation

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#478]
We are hearing from a number of users about this issue.

https://sam.nrel.gov/forum/forum-general/3265

**Comment by sjanzou** [comment]
Running runtime/bin/VC_redist.x64.exe from the installation folder fixed all versions of Windows 10 tested. This is necessary only if missing from the Windows 10 machine. No longer automatically run since requires administrative access.

We can potentially use a different installer and register with the Microsoft Store to avoid issues in the future.

**Comment by cpaulgilman** [comment]
I added instructions for the workaround to the Download page: https://sam.nrel.gov/download.html.
