### ISSUE TITLE
Data tables categories are not clear

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#485]
1. For performance models that do not perform lifetime simulations like PVWatts and Wind that are combined with the Merchant financial plant, lifetime data on the Data Tables is displayed under "2 Minute Data."

2. For the Wind Power model, turbine power curve data appears under "Data: 161 values." A better heading would be "Wind Turbine Power Curve Data".

![image](https://user-images.githubusercontent.com/27711933/102553188-54a02780-4077-11eb-8b2e-605b3dd37fc2.png)

Less critical to fix:

* Physical trough piping header sizing variables (92 values for default case)

**Comment by sjanzou** [comment]
@cpaulgilman, SAM pull request #506 and ssc pull request #515 address this issue. Please review when you get a chance. 
Results for Wind Power/ Merchant Plant:
![image](https://user-images.githubusercontent.com/6498311/105479258-7df93800-5c61-11eb-8c58-b4b3f2506e8f.png)

I did not update the physical trough because of the 2, 11, 19, and 92 data values:
![image](https://user-images.githubusercontent.com/6498311/105479403-a5500500-5c61-11eb-9c55-ddc5cb9ca22f.png)

Note that the merchant plant lifetime data has it's own group label, since it may or may not be the same as the hourly lifetime, etc. for lifetime technology simulations, e.g.
![image](https://user-images.githubusercontent.com/6498311/105479566-d7f9fd80-5c61-11eb-8a24-4f8521ff8fb0.png)

Details in the following Word document...
[GitHubIssuesSAM_485.docx](https://github.com/NREL/SAM/files/5855154/GitHubIssuesSAM_485.docx)

**Comment by sjanzou** [comment]
Closed with ssc PR #515 and PR # 516 and SAM PR #506 and SAM PR #508
