### ISSUE TITLE
Rate switching under TPO PPA

### ISSUE THREAD

**Issue by bradheavner** [NREL/SAM#492]
In the Distributed - Third Party model, there should be an option for commercial customers that finance a behind the meter system with a TPO PPA to have a different rate before and after solar. When solar providers propose to install a system under a PPA for a commercial customer, they often recommend that the customer switch to a solar-friendly rate. Without that there may not be customer savings.

**Comment by cpaulgilman** [comment]
It should be striaghtforward to modify the Value of RE macro to work with the TPO Host / Developer model.

**Comment by cpaulgilman** [comment]
@brtietz Following up on our email conversation.

For the value of RE macro output table, I want to be able to show how the annual bill is calculated for all metering options (net metering, net billing, etc). That requires showing the true-up compensation amount when it applies so that the sum of values in the top table equals "Total bill." For example, it works for net energy metering with no rollovers:

![image](https://user-images.githubusercontent.com/27711933/106046302-ee0b2200-6096-11eb-8d8b-18ebab8be30f.png)

For "Net billing with carryover to next month" `ur_metering_option=3`, true-up payments are not reported, so the values in the table do not add up:

![image](https://user-images.githubusercontent.com/27711933/106046686-71c50e80-6097-11eb-9601-d2f172a26ca9.png)

If I understand correctly, for the remaining metering options (including net metering with excess generation credit rollover), these credits are absorbed by the energy charge portion of the bill, so do not need to be reported separately.

Here is the .sam file I am using to test the Value of RE macro for different scenarios. The latest version of the macro for testing is in my latest commit to https://github.com/NREL/SAM/tree/SAM492_value-of-re-macro-for-tpo:

[value-of-re-macro-tests.zip](https://github.com/NREL/SAM/files/5882819/value-of-re-macro-tests.zip)

Thanks,
Paul.
