### ISSUE TITLE
For PPA models, add maximum debt fraction for DSCR debt option

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#550]
**Background**

In DSCR input mode (basic sculpted debt where the debt size is determined from cash available for debt service instead of specified as a percentage of the installed cost), if the PPA price is high enough, it is possible for the resulting debt percent to exceed 100% without the user noticing.

In some cases, for users experienced with financial modeling, it may be useful to run parametric simulations that how metrics like PPA price, NPV, and LCOE vary over a range of PPA prices when the debt fraction is allowed to exceed 100%.

**Task**

Add a "Limit debt fraction" check box and "Maximum debt fraction" input to the Financial Parameters page.

**Comment by sjanzou** [comment]
ssc pull request 645 and SAM pull request 734 go with this issue.

Note that we currently do not allow negative DSCR as input. However, negative DSCR can be calculated depending on the case. Attached is a SAM file used to test the implementation. 


We should discuss using negative DSCR in general
[Limit_debt_fraction_for_dscr.zip](https://github.com/NREL/SAM/files/7496864/Limit_debt_fraction_for_dscr.zip)


In case anyone is interested in sculpted debt:
![image](https://user-images.githubusercontent.com/6498311/140740955-10a221db-6048-4c3c-9b76-43c363c49ccd.png)

No limit with a low DSCR of 0.2
![image](https://user-images.githubusercontent.com/6498311/140741070-52e6c916-2226-4731-9bcf-a83603872cce.png)

Add limit of 100%
![image](https://user-images.githubusercontent.com/6498311/140741150-4d4d3914-d7ce-4fa7-babc-b5ba97efc68f.png)

Limit 50%
![image](https://user-images.githubusercontent.com/6498311/140741512-702b38eb-fac6-479c-96da-75d749afb96f.png)

If a fixed ppa price is specified, then the debt percantage may not be exactly met due to the debt sizing dependency on the CAFDS value which may or may not be able to cover the expenses (i.e. negative debt). Test cases in sam file attached above. This may warrant a separate issue that we discuss with Financial specialists.

**Comment by cpaulgilman** [comment]
Showing the minimum DSCR and debt fraction in the Metrics table (depending on the debt option input choice) should help with both the negative DSCR and debt fraction > 1 issue.
