### ISSUE TITLE
Solar Resource File Converter Macro - Three New Columns in SolarAnywhere Format

### ISSUE THREAD

**Issue by KWagnerCPR** [NREL/SAM#554]
**Feature Request**
After the upcoming release of SolarAnywhere V3.5, ALL SolarAnywhere format files will include three additional columns (T, U, and V). These will be for Albedo, Particulate Matter 10, and Particulate Matter 2.5. I'd like to request that the SAM team updates the solar resource file converter Macro so that it can handle these additional columns before the release of SolarAnywhere V3.5. 

**Describe the solution you'd like**
I would like to be able to use the Solar Resource File converter to convert the updated SolarAnywhere format files to samcsvs. I would like for the samcsvs to contain the Albedo, PM 10, and PM2.5 columns even if SAM does not currently have a use for particulate matter data. 

**Describe alternatives you've considered**
Not applicable. 

**Additional context**
I've attached a sample SolarAnywhere format file that contains the three additional columns of data. 

[Lake Placid New York United States SolarAnywhere Time Series 20130220 to 20210101 Lat_44_285 Lon_-73_995 SA format TEMPLATE_PM+Albedo.xlsx](https://github.com/NREL/SAM/files/6087116/Lake.Placid.New.York.United.States.SolarAnywhere.Time.Series.20130220.to.20210101.Lat_44_285.Lon_-73_995.SA.format.TEMPLATE_PM%2BAlbedo.xlsx)

**Comment by cpaulgilman** [comment]
This should be a straightforward update, just adding the three columns.

Here is a file with the same data as CSV: [sample-solaranywhere-v3.5-csv.zip](https://github.com/NREL/SAM/files/6087399/sample-solaranywhere-v3.5-csv.zip)

**Comment by cpaulgilman** [comment]
@KWagnerCPR This Version 3.5 example file has a couple of other new features that will require changes to the macro:

* 30-minute time steps

* First time step is for 02/20 00:30 (instead of 01/01 01:00)

I can revise the macro to handle up to one-minute time steps. Should the macro expect different files to have different time steps or do all v3.5 files contain 30-minute data? Will the time stamp of the first row always be for the first time step of the day (01:00 for hourly, 00:30 for 30-minute, 00:15 for 15-minute, etc.) or might the first row start on an arbitrary time step?

For now, SAM requires a weather file that contains one complete year of data from January 1 to December 31, so the macro will have to handle the partial year of data at the beginning of these files. As far as I can tell, for the older SolarAnywhere versions, multi-year time series files started at the first time step of January 1 and sometimes ended partway through the final year, so the macro created a file with "_part" appended to the name for the last partial year of data. It looks like we will need to modify the macro to do something similar for the beginning of the file.

**Comment by KWagnerCPR** [comment]
Hey Paul,

**RE: 30 Minute Time Steps**
All SolarAnywhere format time series files can be downloaded from our UI in 15-min, 30-min, and 60-min resolution (TGY files will always be in hourly resolution). It would be great if the macro could handle all three of these options. Yes, the first row will always start with the first time step of the day, so 0:15 for 15-minute resolution files, 0:30 for 30-min resolution files, or 01:00 for hourly resolution files. 

**RE: Mid-Year First Time Step**
When you go to download time series SolarAnywhere data in any version you can specify the date range you would like to download. This means the files can start and end at any month, day and year after January 1, 1998. I like your plan to mimic the behavior of adding "_part" to the end of partial year Samcsv files from the beginning and the end of the time range. 

Thanks, 

Kristen

**Comment by KWagnerCPR** [comment]
@cpaulgilman Thank you! We released SolarAnywhere V3.5 last Wednesday so the timing is perfect.

**Comment by williamhobbs** [comment]
I'm having problems related to this change. Should I open a new issue?

When I download SolarAnywhere V3.5 data and _don't_ include Particulate matter in the download settings, I get an error when running the converter macro. 

![image](https://user-images.githubusercontent.com/45701090/165370217-4a3cce4d-59b0-479b-9b3f-7ace374adb28.png)

If I comment out the macro code related to PM (lines 446, 447, 470, 471, 484, 485), it runs without errors. 

I'll also note that the SolarAnywhere weather file contains header items for PM (`Particulate Matter 10 (µg/m3),Particulate Matter 2.5 (µg/m3)`) and extra commas on the rows below for those columns. 

I don't think I'm allowed to post SolarAnywhere files. You may be able to replicated this by taking the .xlsx file @KWagnerCPR posted above, converting to .csv, and deleting values for the two PM rows.
