### ISSUE TITLE
Generate Code does not recognize metric_table function

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#558]
**Describe the bug**
Generating code from a SAM case throws a callback error on Metrics when it encounters the metric_table function used to mark unique tables on the Summary page

**To Reproduce**
1. Open a ME Wave case
2. Click Generate Code and generate a JSON for inputs
3. See error below
4. Resulting json output file does not generate any metrics or metric labels after the metric_table command

**Screenshots**
![image](https://user-images.githubusercontent.com/54449384/110503597-96120300-80b9-11eb-9f73-83ca57bdb52c.png)

**Comment by sjanzou** [comment]
Working with all inputs and outputs listed in Data Tables - note that some in ME configurations are not computed in SDKTool runs since the <NULL> outputs in the lk script are not listed as compute module inputs or outputs and only calculated in equations
![image](https://user-images.githubusercontent.com/6498311/141779398-8c1db1a7-621d-44c0-98bd-770d4ec0660b.png)

**Comment by sjanzou** [comment]
SAM project file used to test #685 and #558
[test_SAM_558.zip](https://github.com/NREL/SAM/files/7538590/test_SAM_558.zip)
