### ISSUE TITLE
Add support for inverters with more than 4 MPPT inputs

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#583]
Some inverters on the market have more than four MPPT inputs, such as the SMA Sunny Tripower Core 1, which has six.

https://sam.nrel.gov/forum/forum-general/3388

Supporting more MPPT inputs requires supporting more than four subarrays, which would require redesigning the System Design input page to be more flexible and managing a larger number of input and output variables. Subarray inputs and outputs are currently implemented as single values, but it may make sense to implement them as arrays. For example, a single array to store the number of modules per string input or operating voltage output for each subarray instead of separate variables for each subarray.

See also:

https://github.com/NREL/SAM/issues/396

https://github.com/NREL/SAM/issues/215

https://sam.nrel.gov/forum/forum-general/2907

**Comment by python1981** [comment]
This would be a fantastic enhancement! The ultimate would be the option to add an arbitrary number of MPPTs but I realise this could be challenging.

We have found some scenarios where it is very helpful to calculate many MPPTs - even more than real hardware would allow. For example, when modelling optimizer/micro-inverter systems where there are multiple different panel orientations within individual strings/mppts, it is necessary to break the string into smaller groups and simulate each orientation as a separate MPPTs so the correct orientation can be specified (since each MPPT can only have a single orientation). This workaround allows all panels to use the correct orientation for generation calculations, whilst keeping them all under a single inverter so that inverter clipping is applied correctly.

**Comment by cwhanse** [comment]
@cpaulgilman @janinefreeman FYI, we have "published" an extension of the inverter model to multiple MPPT, which uses the CEC parameters to [pvlib-python](https://github.com/pvlib/pvlib-python/blob/709daa6f8feddb50ae50b1da13f5f720d8ebb78f/pvlib/inverter.py#L140).  In my opinion this model has a stronger basis than what I think SAM does currently (average power and voltage over arrays to get single inputs to the Sandia inverter model). I intend to document the extended model once we've done some lab work to demonstrate it's validity.

**Comment by cpaulgilman** [comment]
Duplicate of https://github.com/NREL/SAM/issues/215
