### ISSUE TITLE
Add Nonbypassable Energy Charge to Utility Rate Calculations

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#615]
This is specific to Net Metering dialogues. A nonbypassable energy charge is a volumetric energy rate that a customer pays on every kilowatt-hour of electricity they consume from the grid (i.e., their grid consumption); however, unlike a traditional volumetric energy charge, the charge cannot be offset by receiving credits for DPV. California’s NEM 2.0 features this. It essentially converts NEM into Net Billing but without the public backlash! See Section [4.2.13 of this report](https://www.nrel.gov/docs/fy20osti/75283.pdf) and [this link](https://www.aurorasolar.com/blog/the-ultimate-guide-to-nem-2-0-part-1-non-bypassable-charges/) for more information.

**Comment by brtietz** [comment]
Reopening this because Duke Energy has some active tariffs that require $/kW fixed charges that are only applicable for solar customers. Similarly, some utilities (Xcel Colorado) have flat $ charges that only apply to solar customers. We may need to do this for bill savings calculations - I'll remove the wishlist tag when funding is confirmed.

URDB might add these under "Other Fixed Charge Attributes" specific names TBD
