### ISSUE TITLE
Power Tower Cycle Gross Capacity on System Costs page does not update

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#631]
### Describe the bug

For the Power Tower model, the cycle gross capacity calculated value does not change with the design turbine gross output variable on the Power Cycle page.  

### To Reproduce

1. Create default Power Tower / Single Owner case.
2. Compare design turbine gross output on System Design page to cycle gross capacity on System Costs page: Both are 115 MWe.
3. On the System Design page, change design turbine gross output to 120 MWe. Cycle gross capacity on System Costs page is still 115 MWe, but $/kWe power cycle costs are calculated based on 120 MWe value.

### Expected behavior

Cycle gross capacity on System Costs page should change with design turbine gross output on System Design change.

### Operating System and Version

 - Tested in Windows
 - SAM 2020.11.29 r2

### Additional context

Need to make sure this works for all tower configurations.

**Comment by tyneises** [comment]
I think this UI equation was inadvertently cut out during this merge: https://github.com/NREL/SAM/commit/777e39ac18cb3d8a7594e3bbe106f85bd953e3d2#diff-9fa19165cbc5ba729e704375d2693b527af67019462aec89a5c7e740734f4e2d

Tower height was fixed in another commit, but in additional to reported cycle capacity described above, the following reported values on the System Cost page do not update:
- receiver area
- storage capacity

I don't think this actually affects the calculated cost values, because those are calculated in a callback that seems to use different, correct inputs.

**Comment by cpaulgilman** [comment]
Mentioned in https://sam.nrel.gov/forum/forum-general/3525

**Comment by tyneises** [comment]
fixed here: https://github.com/NREL/SAM/commit/8c82950abff6618f5f2cea449d3b509f8d6f8286
