### ISSUE TITLE
New Device Library structure for easily saving custom devices

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#657]
### Is your feature request related to a problem? Please describe.

Users would like to have more streamlined ways of importing their own devices (wind turbines, wave energy converters, etc.) to the device library files so that they can be saved in the library for future use. 

### Describe the solution you'd like

A different storage system for device libraries that would not be overwritten by SAM patches or tied to the release version. 

### Describe alternatives you've considered
UI widgets could be used to modify the existing device libraries but these changes would be overwritten every time a SAM version is issued a patch. 
### Additional context
We have had requests from NREL marine energy and wind teams about this type of functionality.

**Comment by mjprilliman** [comment]
@cpaulgilman Just a placeholder issue for thoughts on device libraries. There have now been requests for the wave energy converter library and the wind turbine library.

**Comment by cpaulgilman** [comment]
The current implementation of the weather file library for solar resource data stores data outside of the SAM installation folder so that it can be used by different versions of SAM. We could use a similar approach for equipment libraries.

The module and inverter libraries contain data that is not provided in the CEC Excel file or on manufacturer datasheets, but that can be generated by SSC compute modules. The "with user-entered specifications" options on the Module and Inverter input page could be used as a tool to add items to a user library: The user populates inputs on the UI form and then clicks an "Add to Library" button.

Equipment data should be stored in a standard format that is easily editable (CSV, JSON, or similar).

Need to consider how/whether to maintain an "official" library with data generated by the NREL SAM team separately from a user-generated library.

Could generate and store NREL library data online so that it can be maintained independently of SAM releases, and potentially by users and partners outside of the NREL SAM team. Would require a "Check for Updates" function in SAM, perhaps a button on the relevant input page.

Should check in with other organizations with equipment databases for potential collaboration or integration. Some examples:

* Solar Power World Online: https://www.solarpowerworldonline.com/solar-power-worlds-2016-list-of-solar-inverter-models/ (seems like CEC data and out of date)

* ENF: https://www.enfsolar.com/pv/solar-system

* Photon: https://www.photon.info/en/photon-databases

**Comment by cpaulgilman** [comment]
I agree that this is a large effort. I think we can keep it as an issue to address when we have the resources.
