### ISSUE TITLE
Clean up O&M costs

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#659]
Current implementation of O&M costs is hacky, so we want to do a systematic refactoring of the O&M cost code. Notes from 10/22/2020 meeting:

* Consider replacing SSC variable names like om_capacity1 with more meaningful names like om_capacity_battery to make it easier for SDK users to understand variable names. This is partially done in https://github.com/NREL/SAM/pull/529, but om_opt_fuel_1_, om_production1 remain.

* Consolidate variable assignments into one place (common.cpp?) rather than in each financial model (singleowner.cpp, etc.) so that these variables are available to all technology and financial models as needed.

* Treat "normal" O&M costs, fuel cell O&M costs, biopower feedstock costs, and CSP fuel costs in a consistent way.

* Make sure O&M costs are shown correctly in the cash flow for all financial models, and in send-to-Excel with Equations spreadsheets. Also consider renaming cash flow variables from names like cf_om_capacity1_expense to cf_om_battery_capacity_expense. This is done in https://github.com/NREL/SAM/pull/936 and https://github.com/NREL/SAM/pull/927.

* Update versions.lk to handle any variable name changes.

**Comment by sjanzou** [comment]
Building on the bullet points, an excerpt from cmod_cashloan:
![image](https://user-images.githubusercontent.com/6498311/222690646-4d0a813f-25cf-4ac8-83e8-447e083bde71.png)

om_fixed1,2, om_production1,2, om_capacity1,2

Also, note that production arrays from technology models have both nyears (analysis period) and nyears+1 lengths. This is confusing to debug and leads to several memory exceptions. Maybe we should standardize on nyears + 1 for financial startup costs and for technology startup consumption (e.g. fuelcell_discharged).

common.cpp or common_financial.cpp seem reasonable - common.cpp may be preferable since o and m can be used for dispatching in technology models.

**Comment by brtietz** [comment]
@sjanzou Since we sometimes need to run multiple technology models, we previously decided that annual arrays coming out of technology models should be nyears, and financial models should be responsible for pre-pending year 0. See discussion here: https://github.com/NREL/ssc/issues/601

And implementation for the battery here: https://github.com/NREL/ssc/pull/641

**Comment by sjanzou** [comment]
> @sjanzou Since we sometimes need to run multiple technology models, we previously decided that annual arrays coming out of technology models should be nyears, and financial models should be responsible for pre-pending year 0. See discussion here: [NREL/ssc#601](https://github.com/NREL/ssc/issues/601)
> 
> And implementation for the battery here: [NREL/ssc#641](https://github.com/NREL/ssc/pull/641)

But the fuel cell has nyears+1 coming out of the technology model. Do we need a separate compute module to re-align before calling the financial models? We need to handle the exceptions consistently somewhere...

**Comment by cpaulgilman** [comment]
Feedback from @williamhobbs on whether fuel cell fuel cell annual arrays require Year 0 (length of nyears+1): "I can't think of a reason that a fuel cell would have an extra year in the analysis period, so I'm fine with modifying it to have the same convention as other technologies."

**Comment by sjanzou** [comment]
> @sjanzou Since we sometimes need to run multiple technology models, we previously decided that annual arrays coming out of technology models should be nyears, and financial models should be responsible for pre-pending year 0. See discussion here: [NREL/ssc#601](https://github.com/NREL/ssc/issues/601)
> 
> And implementation for the battery here: [NREL/ssc#641](https://github.com/NREL/ssc/pull/641)

FYI - The prepending is currently done in both technology and financial compute modules
<img width="632" alt="image" src="https://github.com/NREL/SAM/assets/6498311/26fa1761-8767-4b22-8352-d7a667aa1236">
