### ISSUE TITLE
Metrics tables not displaying proper label for NaN values

### ISSUE THREAD

**Issue by mjprilliman** [NREL/SAM#771]
### Describe the bug
The metrics tables from metrics.lk do not display the specified label when the output value is NaN. This appears to be an issue with the metric() function, whereas the metric_row() function displays the label from metrics.lk even if the output value is NaN. 
### To Reproduce

1. Go to PV Battery, Single Owner case
2. Set ppa_price_input to 0
3. Simulate
4. See 'flip_actual_irr' where 'Internal rate of return (IRR)' should be 

![image](https://user-images.githubusercontent.com/54449384/141857067-c948d4df-9d1b-4ae6-a157-d79321d50797.png)

### Expected behavior
Label showing with NaN value such as in this screenshot for 'Developer internal rate of return'. This example uses metric_row() on line 31 of metrics.lk, where the first example uses metric() on line 63

![image](https://user-images.githubusercontent.com/54449384/141857098-d1b5b3bd-bf9a-4360-ae38-a76749af13f3.png)

**Comment by sjanzou** [comment]
Updated and fixed in pull request #773 
<img width="488" alt="image" src="https://user-images.githubusercontent.com/6498311/141924401-785258a3-f617-4199-980f-3a1b0a750caa.png">

No effect on previously correct additional metric tables
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/6498311/141924469-e0eb9341-6a03-4c9b-8fb6-3c7c3de37665.png">
