### ISSUE TITLE
Page notes don't transfer to a new page in version upgrade when UI page is deleted

### ISSUE THREAD

**Issue by janinefreeman** [NREL/SAM#796]
Page notes that were assigned to a UI page that no longer exists in a newer version of SAM get deleted when you upgrade that file to a new version. We should figure out some kind of check for this- at the very least, let's warn the user. Ideally we would move it to a new page, but that might create a sort of complex mapping paradigm we might not want. Example: create a note on the "System Costs" page in 2020.11.29 and open it in the newest Beta.

@cpaulgilman would appreciate your thoughts on how to handle this.

**Comment by cpaulgilman** [comment]
I don't think the pagenote() function will work in the versions.lk context because versions.lk runs before the case is open, so show_page() can't access UI pages. Here's how it would work from an LK script after a case is open:

```
// read what's written in the page note on the System Design input page
show_page('System Design');
str = pagenote();
outln(str);
```

As far as desired behavior, maybe append the page note text to whatever is the first UI page in the case so it will work across all configurations?

@janinefreeman Can you provide a .sam file for testing?

**Comment by janinefreeman** [comment]
The file I was using is: https://github.com/NREL/SAM/blob/develop/samples/Excel%20Exchange/excel-exchange-example.sam

**Comment by sjanzou** [comment]
Fixed in pull request 809
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/6498311/143672389-41ac0808-694f-4419-a151-241defbba68f.png">
