### ISSUE TITLE
Simulation hangs at 66.6% when PV lifetime daily losses are enabled

### ISSUE THREAD

**Issue by cpaulgilman** [NREL/SAM#976]
### Describe the bug

For some PV Battery cases, setting lifetime daily AC losses causes simulation to stop indefinitely.

https://sam.nrel.gov/forum/forum-general/3784

### To Reproduce

1. Create a default PV Battery / Single Owner case or PV Battery / Commercial case.
2. On the Lifetime and Degradation page, click **Enable lifetime daily AC losses** and then click **Edit lifetime data**.
3. For Rows 1-5 in the AC Loss table, enter 100.
4. Click **OK** and run a simulation.

Workaround is to use "system availability" losses on Losses page. (This option applies the same loss throughout the lifetime simulation, so does not offer the option to have the loss change from year to year.)

### Expected behavior

Simulation should complete and AC output should be limited by the loss values entered.

### Additional context

Issue applies to SAM 2021.12.02 and SAM 2021.12.02 r1, but not SAM 2020.11.29 r2.

This issue only seems to affect PV Battery, not Detailed PV configurations.

Note that simulation does finish if Rows 10-15 are set to 100% instead of Rows 1-5.

Need to check for DC lifetime losses as well.

**Comment by brtietz** [comment]
This was due to a stack overflow in the powerflow code - the daily losses were included in a calculation that caused infinite recursion.

In addition to that, it looks like the daily losses don't play nicely with the grid outage code: 

![image](https://user-images.githubusercontent.com/5530592/157555086-ea040367-9baa-45d7-aa97-2c6e735e0204.png)

With a grid outage and a 100% daily loss, the critical load should be unmet, and the to/from grid values should be zero. I'll fix that in the same pull request.

**Comment by brtietz** [comment]
Closed in https://github.com/NREL/ssc/pull/780
