### ISSUE TITLE
CEC inverter file has 1486 entries with too low Idcmax

### ISSUE THREAD

**Issue by d5ch4k** [NREL/SAM#98]
e.g. Line 17: ABB: PVI 3.0 OUTD-S-US-Z-M-A (208V) 208V [CEC 2016] shows **Idcmax=0.00625 A**

an operating range check for these modules cannot be made.

a closer look shows, that these rather small values seem to be calculated by: (Paco/1000)/Vdcmax which is at least by a factor 1000 too low

**Comment by cpaulgilman** [comment]
SAM's detailed photovoltaic model does not use the Idcmax parameter, so we have chosen to include inverters with these unrealistic values from the CEC Excel workbook in SAM's library. About a quarter of the inverters in the SAM 2018.11.11 inverter library seem to have unrealistic Idcmax values.

For this particular inverter, the value of 0.00625 does appear to be Paco / Vdco / 1000. However, the value of Idcmax for the 2014 version of the inverter is 20 A, and I would expect Idxmax = Pdco / Vdco rather than based on Paco, so I'm not sure we should try to change the unrealistic Idcmax values until we have more information about where they came from.

**Comment by d5ch4k** [comment]
Is it possible to keep them empty as long as they are that far away?

**Comment by cpaulgilman** [comment]
This has been resolved by using only data from the most recent CEC database. Older versions of SAM accumulated data from older versions of the database, but from now on, the inverter library will contain only data from the current CEC database (3/1/2019 version in latest update).

aa60bc3b4262838faad759926cc9ee1876fc0f6a
